
SRC = driver.cpp YAKL.cpp
EXE = swm

default: main

CXX = mpic++
LINK = ${CXX}
CXXFLAGS = -O0 -I${PNETCDF_PATH}/include -std=c++11 -DARRAY_DEBUG -g
# CXXFLAGS = -O3 -I${PNETCDF_PATH}/include -std=c++11
LDFLAGS = -L${PNETCDF_PATH}/lib -lpnetcdf

OBJ = $(notdir $(SRC:.cpp=.o))

main: $(EXE)

$(EXE): $(OBJ)
	$(LINK) $(EXTRA_PATH) $(OBJ) $(LIB) -o $(EXE) $(LDFLAGS)

%.o:%.cpp *.h
	$(CXX) $(CXXFLAGS) $(EXTRA_INC) -c $< -o $(notdir $@)

clean:
	rm -f *.o swm


