
SRC = driver.cpp YAKL.cpp
EXE = swm

default: main

CXX = nvcc -ccbin mpic++
LINK = ${CXX}
CXXFLAGS = -I./cub --expt-extended-lambda -arch sm_50 -O3 -I${PNETCDF_PATH}/include -std=c++11 -D__USE_CUDA__
CUDAFLAGS = -x cu
LDFLAGS = -L${PNETCDF_PATH}/lib -lpnetcdf

OBJ = $(notdir $(SRC:.cpp=.o))

main: $(EXE)

$(EXE): $(OBJ)
	$(LINK) $(OBJ) $(LIB) -o $(EXE) $(LDFLAGS)

%.o:%.cpp *.h
	$(CXX) $(CUDAFLAGS) $(CXXFLAGS) -c $< -o $(notdir $@)

clean:
	rm -f *.o swm


